server:
    port:  443
gcp:
    projectid:  "altethical"
    projectnum: "968747045906"
    databaseurl:   "https://altethical.firebaseio.com"
    storagebucket: "altethical.appspot.com"
    secretname: "jwtkey"
