server:
    port:  443
gcp:
    projectid:  "joshcarp-altethical"
    projectnum: "968747045906"
    databaseurl:   "https://joshcarp-altethical.firebaseio.com"
    storagebucket: "joshcarp-altethical.appspot.com"
    secretname: "jwtkey"
