name: Docs
on:
    push:
        branches: [ master ]
        paths:
        - 'proto/*'
        - 'sysl/*'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: joshcarp/altethical.wiki
          path: altethical.wiki
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: altethical
      - name: remove old service docs
        working-directory: altethical.wiki
        run: |
          rm -rf service-documentation
      - name: Gen Docs
        working-directory: altethical
        run: |
          make docs -B
          mv service-documentation ../altethical.wiki
      - name: git add
        working-directory: altethical.wiki
        run: |
          git config --global user.email "joshuacarpeggiani@gmail.com"
          git config --global user.name "Sync Action"
          git add -A
          git commit -m "Update service documentation"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: joshcarp/altethical.wiki
          directory: altethical.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
